name: Test Graspi
on: [push, pull_request]
jobs:
  pygraspi-nix-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --command "py.test --cov-fail-under=100"
      - run: nix-shell --pure --command "black --check setup.py pygraspi"
      - run: nix-shell --pure --command "nbqa pylint notebooks/intro.ipynb"
      - run: nix-shell --pure --command "nbqa flake8 notebooks/intro.ipynb"
      - run: nix-shell --pure --command "nbqa black notebooks/intro.ipynb"
      - run: nix-shell --pure --command "nbqa isort notebooks/intro.ipynb"
#     - run: nix-shell --pure --command "pylint setup.py pygraspi"
#     - run: nix-shell --pure --command "flake8 setup.py pygraspi"
