name: Test PFHub Package
on: [push, pull_request]
jobs:
  pygraspi-nix-test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --command "echo 'hello world'"
