name: Test PFHub Package
on: [push, pull_request]
jobs:
  pygraspi-nix-test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: pygraspi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-shell --pure --command "python -c 'import send2trash; print(send2trash.__path__)'"
      - run: nix-shell --pure --command "jupyter notebook --no-browser"
